[DI - Step 1] 티버 미션 제출합니다
woowacourse/jwp-di pull request #31
Opened 2019-11-05 07:25 UTC by yjll1019

감사합니다 :)

2019-11-06 00:11 UTC, young891221 requested changes
안녕하세요 티버님!
미션 구현은 잘 해주셔서 코멘트 하나 남겼습니다 👍 
커밋이 다른분의 아이디로 되어 있는데요. 페어 프로그래밍으로 진행해서 그런 부분일까요?
확인해 보시고 반영 부탁드립니다~!

2019-11-06 00:11 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanScanner.java
> +        return getTypesAnnotatedWith(Controller.class, Service.class, Repository.class);
해당하는 어노테이션에 대해서 전환한 예제 + 테스트 케이스가 추가되었으면 합니다ㅎㅎ

2019-11-12 04:58 UTC, yjll1019 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanScanner.java
> +        return getTypesAnnotatedWith(Controller.class, Service.class, Repository.class);
BeanScanner에 대한 테스트 케이스 추가했습니다!
여쭤보고 싶은 부분이 있는데요~ 
**어노테이션에 대해서 전환한 예제** 이 부분이 어떤 말씀이신지 설명해주실 수 있으신가요...?

2019-11-12 05:05 UTC, yjll1019 commented
안녕하세요~ Havi 님! 
피드백 반영이 늦어져서 죄송합니다 ㅠㅠ
페어랑 미션을 수행한 후 바로 미션을 제출해서 페어의 아이디로만 커밋이 되어있었습니다!  
감사합니다~

2019-11-12 23:58 UTC, pobiconan requested changes
피드백 반영 잘 했네요. 💯
단, 프레임워크 구현하는 목적을 다시 한번 생각해 보면 좋겠네요.
프레임워크를 구현하는 이유는 애플리케이션에서 사용하기 위함인데요. 애플리케이션에서 적용한 부분이 보이지 않네요. slipp 모듈에 지금 구현한 프레임워크 기능을 적용해 보면 좋겠네요.

2019-11-28 00:34 UTC, young891221 approved these changes
리펙토링을 열심히 해주셨네요! 💯 
다음 단계 진행 부탁드릴게요:)

2019-11-28 00:34 UTC, merged