[DI  - Step 1] 이바 미션 제출합니다.
woowacourse/jwp-di pull request #36
Opened 2019-11-06 13:19 UTC by seonghun127

안녕하세요 후니! 리뷰이 이바입니다.
부족한 부분들 많이 지적해주시면 감사하겠습니다.

2019-11-09 11:32 UTC, jeonghoon1107 requested changes
안녕하세요 이바!
구현 잘 하셨네요 👍 
몇가지 피드백 남겼으니 확인부탁드려요 :)

2019-11-09 11:32 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
BeanFactory가 enum인 이유가 있을까요?
애플리케이션이 구동되면서 SlippWebApplicationInitializer은 한번만 실행이 되죠!

2019-11-09 11:32 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            beans.put(clazz, instantiate(clazz, new ArrayList<>(Collections.singletonList(clazz))));
new ArrayList<> 로 한 이유가 무엇인가요?

2019-11-09 11:32 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        for (Class<?> clazz : preInstantiatedBeans) {
preInstantiatedBeans 해당 변수를 사용한 이유가 있나요?
beans라는 변수를 사용하면 좋을 것 같아요.

2019-11-09 11:32 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        if (!injectCtor.isPresent()) {
orElse를 사용해도 좋을 것 같아요!

2019-11-09 11:32 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/InterfaceCannotInstantiatedException.java
> +public class InterfaceCannotInstantiatedException extends RuntimeException {
패키지 구분할 필요가 있어보이네요!

2019-11-09 11:32 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +    private void validateInitialization() {
항상 체크하게 해야할까요?

2019-11-11 06:26 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
일단 `BeanFactory`를 싱글톤으로 만들기 위해서 enum으로 만들었습니다.
그 이유는 빈으로 등록되는 클래스들이 단일 객체임을 보장하기 위함입니다. 빈을 만들어주는 클래스 `BeanFactory`가 싱글톤이라면 그에 등록되는 빈들도 저절로 싱글톤이 보장받을거란 생각을 했습니다.

후니의 피드백을 보고 든 저의 생각은 이렇습니다. `SlippWebApplicationInitializer`가 한번만 실행되는 것은 맞지만 그것이 항상 보장되는 것일까? 와 `BeanFactory`가 다른 곳에서도 호출될 위험이 있을 수 있지 않을까?라는 의문점이 들었습니다. 그러니 싱글톤임을 보장받기위해 싱글톤 패턴을 적용해야한다는 생각입니다.

그런데 현재 클래스 구조는 tomcat에서 `NextstepServletContainerInitializer`를 실행시키고 있어 이에 대한 제어권이 mvc 모듈에게 전혀 없다는 생각이 들었습니다. 이러한 측면에서 생각해보면 tomcat에 의해`SlippWebApplicationInitializer`가 한번만 실행될 것으로 보장받을 수 있기 때문에 `BeanFactory`에 별다른 싱글톤패턴을 적용하지 않아도 된다는 말씀이신가요?

2019-11-11 12:14 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            beans.put(clazz, instantiate(clazz, new ArrayList<>(Collections.singletonList(clazz))));
Set 으로 변경했습니다.
단순히 `Collections`의 `contains()` 메서드만 사용하기때문에 Set으로 확인하는게 더 빠르겠다는 생각을 했습니다.

2019-11-11 12:16 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/InterfaceCannotInstantiatedException.java
> +public class InterfaceCannotInstantiatedException extends RuntimeException {
exception 패키지를 따로 분리했습니다!

2019-11-11 12:46 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
그리고 더 고민해보니 `DispatcherServlet`이 이후에 추가적으로 늘어날 경우에 각각의 `BeanFactory`가 필요할 것이라고 생각합니다.

각각의 서블릿이 `BeanFactory`을 가지고 있어 모듈별로 서로 다른 빈들을 가지고 있어야지, 싱글톤 객체로 존재하게 되면 다른 역할을 하는 서블릿이 가지고 있어야할 빈을 공유하게 됨으로 문제가 발생할 수 있겠다는 생각이 들었습니다.

2019-11-11 12:55 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        if (!injectCtor.isPresent()) {
```
Optional<Constructor> injectCtor = getInjectCtor(clazz.getDeclaredConstructors());
if (!injectCtor.isPresent()) {
    return instantiateUsingDefaultCtor(clazz);
}
```

위 로직에서 orElse를 사용하지 않은 이유는 `getInjectCtor()` 메서드로 인자 주입할 생성자를 찾되 못찾게 되면 `instantiateUsingDefaultCtor()`기본생성자로 객체를 생성하고 위 로직을 가지는 `instantiate()` 메서드를 바로 리턴하기 위함입니다.

`instantiateUsingDefaultCtor()` 메서드의 반환타입과 `getInjectorCtor()`메서드의 반환 타입도 같지않아서 로직을 합칠 수 없었습니다.

2019-11-11 13:07 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +    private void validateInitialization() {
원래는 `BeanFactory`를 싱글턴으로 만들기 위해 enum으로 변경하면서 생성자 주입 방식을 적용할 수 없었습니다. 그래서 초기화를 하는 `initialize()`메서드로 인자 주입을 수행해서 `BeanFactory` 객체를 초기화하기 전에 다른 메서드에 접근할 수 있었습니다. 

그 상황을 제어하기 위해 예외를 확인하는 로직을 두었는데 `BeanFactory`를 enum 방식이에서 다시 일단 클래스로 바꿈으로써 위 메서드를 제거하고 초기화 `initialize()`메서드를 생성자에서 수행하는 방식으로 변경했습니다.

2019-11-11 13:18 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        for (Class<?> clazz : preInstantiatedBeans) {
별다른 이유는 없었습니다..ㅎㅎ
다시보니 `BeanFactory`에서 초기화된 beans 변수를 사용하는게 더 의미적으로 더 맞는거 같네요!

2019-11-12 01:47 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
제 생각으로는 WebApplicationInitializer는 mvc모듈에 들어가는 것이 맞다고 생각합니다.

`그리고 더 고민해보니 DispatcherServlet이 이후에 추가적으로 늘어날 경우에 각각의 BeanFactory가 필요할 것이라고 생각합니다.
`
ApplicationContext를 함께 공부해보시면 좋을 것 같아요.

많은 고민을 하신 것이 느껴지네요!

2019-11-13 00:05 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        if (!injectCtor.isPresent()) {
`
getInjectCtor(clazz.getDeclaredConstructors())
                .map(~~)
                .orElse(instantiateUsingDefaultCtor(clazz));`
위와같이 처리하는 것을 말한 것이에요!

2019-11-13 00:23 UTC, jeonghoon1107 approved these changes
안녕하세요 이바!
깔끔하게 리팩토링 하셨네요 👍 
다음 단계 진행해주세요 :)

2019-11-13 00:24 UTC, merged