[DI - Step 1] 무민 미션 제출합니다.
woowacourse/jwp-di pull request #38
Opened 2019-11-07 11:06 UTC by green4469

2019-11-10 09:28 UTC, kang-hyungu requested changes
안녕하세요 무민 리뷰어 강현구입니다
미션 구현하느라 수고하셨어요 👏 
몇 가지 피드백 남겼으니 수정해보시고 리뷰 재요청주세요!

2019-11-10 09:28 UTC, kang-hyungu commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
enum으로 처리할 필요가 있을까요? enum 용도와 맞지 않는 것 같은데...
싱글톤으로 유지하려고 enum을 쓴걸까요?

2019-11-10 09:28 UTC, kang-hyungu commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            beans.put(clazz, instantiate(clazz, new ArrayList<>(Collections.singletonList(clazz))));
싱글톤 리스트로 감싸고 다시 array list로 풀어야 할까요?
set 으로 계속 사용해도 되지 않을까요?

2019-11-10 09:28 UTC, kang-hyungu commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            if (clazz.isAnnotationPresent(Controller.class)) {
객체지향 생활체조 규칙에 맞춰 수정해보아요
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.

2019-11-10 09:28 UTC, kang-hyungu commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        } catch (Exception e) {
체크 예외와 언체크 예외를 Exception 하나로 다 처리하지 말고 newInstance에서 발생하는 언체크 예외를 처리하도록 수정 해보아요

2019-11-10 09:28 UTC, kang-hyungu commented on nextstep-di/src/test/java/nextstep/di/factory/BeanFactoryTest.java
>  public class BeanFactoryTest {
다음 테스트를 추가해서 인터페이스 인자가 있을 때 빈 생성이 의도한대로 동작하는지 확인이 필요해보이네요
```java
    @Test
    void QuestionRepository가_싱글_인스턴스가_맞는지_테스트() {
        beanFactory.initialize(BeanScanner.scan(basePackages));
        final MyQnaService myQnaService = beanFactory.getBean(MyQnaService.class);

        final QuestionRepository actual = myQnaService.getQuestionRepository();
        final QuestionRepository expected = beanFactory.getBean(JdbcQuestionRepository.class);

        assertThat(actual).isEqualTo(expected);
    }
```

2019-11-11 07:57 UTC, green4469 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
말씀하신대로 BeanFactory 를 싱글톤으로 구현하기 위해 enum 을 사용했습니다. 아래의 자료들을 참고했습니다.

1. _Java Language Specification - Gosling et. al._ 에 기술된 enum 의 특성

> An enum type has no instances other than those defined by its enum constants. It
> is a **compile-time error to attempt to explicitly instantiate an enum type** (§15.9.1).
> 
> In addition to the compile-time error, three further mechanisms ensure that no instances of
> an enum type exist beyond those defined by its enum constants:
> - The final clone method in Enum ensures that **enum constants can never be cloned.**
> - **Reflective instantiation of enum types is prohibited.**
> - Special treatment by the serialization mechanism ensures that duplicate **instances are
> never created as a result of deserialization.**

2. _Effective Java 3rd- Joshua Bloch_ 

> ... This approach may feel a bit unnatural, but a single-element
> enum type is often the best way to implement a singleton. ....

현업에서는 Singleton 구현을 위해 enum 을 사용하지 않나요? 그렇다면 그 이유는 무엇인가요? 궁금합니다~

2019-11-11 08:07 UTC, green4469 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
추후에 생각해보니 BeanFactory 가 싱글턴이면 안 된다는 생각이 들었습니다.

여러 DispatcherServlet 이 톰캣에 물려있다고 생각하면, 각 DispatcherServlet 이 BeanFactory 를 가질 것이고, 싱글턴은 같은 JVM 의 같은 클래스로더일 경우 이를 지원할 수 없기 때문입니다.

이 문제에 대해서는 어떻게 생각하시나요?

2019-11-11 08:29 UTC, green4469 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            beans.put(clazz, instantiate(clazz, new ArrayList<>(Collections.singletonList(clazz))));
중복이 존재하지 않고 contains 메소드만 호출하므로 ArrayList 대신 HashSet 을 사용하도록 리팩토링 했습니다!

2019-12-14 16:43 UTC, green4469 commented on nextstep-di/src/test/java/nextstep/di/factory/BeanFactoryTest.java
>  public class BeanFactoryTest {
미처 인지하지 못하고 있던 부분이네요... 

리뷰어님 말씀대로 해당 테스트를 추가하고 돌려보니 싱글턴이 아니더군요!!

파라미터로 객체를 생성하고 난 뒤 beans 에 추가해주지 않아서 생긴 문제였습니다.

감사합니다.

2019-12-19 21:16 UTC, kang-hyungu commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +public enum BeanFactory {
enum으로 싱글톤 패턴 구현 가능하고 많이 쓰는 방법입니다.
저는 개발할 때 enum은 보통 상수처럼 생각하고 사용하다보니 추가 기능을 많이 두지 않으려는 편이에요.
이부분은 각자 생각이 다를테니 팀에서 협업하실 때 같이 정하시면 좋겠네요.

그리고 BeanFactory는 싱글턴으로 만드는게 더 좋다고 생각해요
클라우드 서비스를 사용하면 여러 대의 가상서버를 띄우기 쉽기 때문에 인스턴스 한대에 여러 JVM을 띄울 일이 없습니다.
굳이 서버 한 대에 여러 WAS를 띄우기 보다 서버를 분리하는 방법으로 해결해도 충분하다고 생각합니다.

2019-12-19 21:21 UTC, kang-hyungu commented on nextstep-di/src/test/java/nextstep/di/factory/BeanFactoryTest.java
>  public class BeanFactoryTest {
moomin-di-step2-tmp 브랜치로 확인해보니 테스트 통과하네요
pr은 moomin-di-step1으로 되어 있으니 저 브랜치로 머지하거나 체리픽해서 반영하고 재요청 주시면 머지할게요!

2019-12-19 21:24 UTC, kang-hyungu commented on nextstep-di/src/test/java/nextstep/di/factory/BeanFactoryTest.java
> +    void QuestionRepository가_싱글_인스턴스가_맞는지_테스트() {
아직 테스트가 깨지네요
moomin-di-step2-tmp 브랜치는 통과하는데 빠진 부분 다시 확인해보면 어떨까요?

2019-12-21 08:02 UTC, kang-hyungu approved these changes
피드백 반영 잘 하셨어요! 👍 
머지 처리 할게요 수고하셨어요!

2019-12-21 08:02 UTC, merged