[DI - step1] 루피 미션 제출합니다.
woowacourse/jwp-di pull request #4
Opened 2019-10-30 08:55 UTC by MrKwon

안녕하세요. 후니님 개발왕이 되고싶은 루피 입니다. 🤠
먼저 미션의 step1 요구사항에 맞춰 구현하였습니다.
그리고 레거시 코드에 DI 를 적용하기 위해 Service 와 Repository 를 구현하였습니다.
감사합니다. ! ㅎㅎ

2019-11-01 09:35 UTC, jeonghoon1107 requested changes
안녕하세요 루피!
리뷰가 늦었습니다 ㅠㅠ
기능 구현은 잘해주셨는데 테스트가 없네요 ㅠㅠ
테스트를 꼼꼼하게 작성해주세요 :)

2019-11-01 09:35 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/controller/ApiUserController.java
> +        mav.addObject("user", userService.findUser(userId));
user가 null이면 어떻게 되나요?

2019-11-01 09:35 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/repository/UserRepository.java
> +public interface UserRepository {
네이밍이 좀 이상한 것 같네요.
Repository라고 하면 어떨까요?
User라는 것을 빼고 더 확장성있게 사용하면 좋을 것 같아요.

public interface UserRepository<T, ID> 처럼 사용해도 좋겠네요!

2019-11-01 09:39 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/controller/UserController.java
> +        User user = userService.findUser(req.getParameter("userId"));
바뀌기 전이 네이밍이 더 명확한 것 같아요!

2019-11-01 09:41 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/repository/UserDaoRepository.java
> +public class UserDaoRepository implements UserRepository {
https://stackoverflow.com/questions/8550124/what-is-the-difference-between-dao-and-repository-patterns/15513290

2019-11-05 04:56 UTC, MrKwon commented on slipp/src/main/java/slipp/controller/ApiUserController.java
> +        mav.addObject("user", userService.findUser(userId));
userDao 를 Optional 로 감싸고 Service 로직에서 null 일 경우 exception 을 처리하도록 하였습니다.

2019-11-05 05:10 UTC, MrKwon commented on slipp/src/main/java/slipp/repository/UserRepository.java
> +public interface UserRepository {
Repository 로 변경 후 annotation 을 사용할 때 FQCN 으로 변경하였습니다.

2019-11-05 05:19 UTC, MrKwon commented on slipp/src/main/java/slipp/controller/UserController.java
> +        User user = userService.findUser(req.getParameter("userId"));
넵, 다시 변경 했습니다😂

2019-11-06 02:00 UTC, MrKwon commented
<img width="599" alt="Screen Shot 2019-11-06 at 10 59 21 AM" src="https://user-images.githubusercontent.com/32266963/68261788-8c6f2a00-0084-11ea-8d05-42278c1a6e20.png">
<img width="601" alt="Screen Shot 2019-11-06 at 10 59 29 AM" src="https://user-images.githubusercontent.com/32266963/68261790-8ed18400-0084-11ea-96c0-d6ec6929df7f.png">

DM 으로 추가적인 피드백을 주셔서 첨부합니다.

2019-11-06 04:28 UTC, MrKwon commented
안녕하세요 후니~ 루피입니다.🤠
피드백 반영하였습니다.
bean 들이 싱글 인스턴스인지 확인하는 테스트와 Controller, Service, Repository 를 정상적으로 스캔하는지에 대한 테스트도 추가하였습니다.

2019-11-09 08:15 UTC, jeonghoon1107 approved these changes
안녕하세요 루피!
몇가지 피드백남겼으니 다음 단계에서 반영해주세요 :)
혹시 피드백이 이해가 되지 않으셨거나 다른 의견있으면 말씀해주세요!

2019-11-09 08:15 UTC, jeonghoon1107 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        BeanFactory beanFactory = new BeanFactory(beanScanner.getBeans());
BeanFactory를 AnnotationHandlerMapping에서 생성하는 이유가 있나요?

이전에 DM으로 얘기하였었는데, 혹시 다른 의견이 있으시거나 피드백을 이해하지 못하셨으면 말씀해주세요!

2019-11-09 08:15 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            Object instance = BeanUtils.instantiateClass(preInstanticateBean);
최대한 외부 의존성은 빼고 구현하면 좋을 것 같아요!

2019-11-09 08:15 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        RowMapper<User> rm = rs -> new User(rs.getString("userId"), rs.getString("password"),
이전 단계에서 배웠던 reflection을 이용해 바꾸어 보면 어떨까요?

2019-11-09 08:15 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/repository/Repository.java
> +public interface Repository {
Repository를 Interface로 뺐지만 확장성이 없네요.
예를 들어 User가 아닌 Article이라는 객체를 사용해야할 때 똑같이 Interface를 하나 더 만들어야 할까요?

Repository의 메서드에서 User만 받게하는 것보다 확장성이 있으면 좋을 것 같아요.

2019-11-09 08:15 UTC, merged

2019-11-09 13:52 UTC, jeonghoon1107 commented
> <img alt="Screen Shot 2019-11-06 at 10 59 21 AM" width="599" src="https://user-images.githubusercontent.com/32266963/68261788-8c6f2a00-0084-11ea-8d05-42278c1a6e20.png">
> 
> <img alt="Screen Shot 2019-11-06 at 10 59 29 AM" width="601" src="https://user-images.githubusercontent.com/32266963/68261790-8ed18400-0084-11ea-96c0-d6ec6929df7f.png">
> 
> DM 으로 추가적인 피드백을 주셔서 첨부합니다.

제가 표현을 잘못했네요 ㅠㅠ AnnotationHandlerMapping 에서 BeanFactorty 를 생성하는 것을 말한 것이었어요!

2019-11-20 04:23 UTC, MrKwon commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        BeanFactory beanFactory = new BeanFactory(beanScanner.getBeans());
피드백 반영하였습니다. 현재 onStartup 메서드에서 생성하여 AnnotationHandlerMapping 으로 주입하도록 변경하였습니다.

2019-11-20 04:26 UTC, MrKwon commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            Object instance = BeanUtils.instantiateClass(preInstanticateBean);
이 부분은 요구사항의 힌트에서 사용해도 괜찮다고 하셔서 사용하였습니다.

<img width="816" alt="Screen Shot 2019-11-20 at 1 25 07 PM" src="https://user-images.githubusercontent.com/32266963/69209067-38db0100-0b99-11ea-8c7d-c7928015e127.png">

2019-11-20 04:28 UTC, MrKwon commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        RowMapper<User> rm = rs -> new User(rs.getString("userId"), rs.getString("password"),
이 부분은 지난 jdbc 미션에서 reflaction 을 이용해 구현한 바가 있었습니다.

이번 미션에서 집중해야 되는 부분이 di 이기 때문에 해당 미션에서는 di 에 집중하고 있습니다.

2019-11-20 04:29 UTC, MrKwon commented on slipp/src/main/java/slipp/repository/Repository.java
> +public interface Repository {
Generic 을 이용해 Repository 가 User 외에 다른 클래스도 이용할 수 있도록 변경해보았습니다.