[DI - step1] 르윈 미션 제출합니다
woowacourse/jwp-di pull request #40
Opened 2019-11-08 16:19 UTC by yuyu154

안녕하세요!
미션 제출이 많이 늦었습니다 ㅠㅠ

1. ```BeanFactory```를 재귀 방식으로 구현했는데 로직이 복잡한 부분
2. ```AnnotationHandlerMapping```에 외부에서 Controller에 대한 bean을 주입하는 부분

위의 두 부분에 대해서 고민을 많이 했고 아직 고민중입니다... 
관련해서 피드백을 받고 싶습니다
 
감사합니다!

2019-11-10 12:40 UTC, phs1116 requested changes
안녕하세요! 르윈.
전체적으로 구현 잘해주셨어요. 👍 
고민하신 사항에 대해서 몇 가지 피드백 추가했는데 참고 부탁드릴게요. :)

2019-11-10 12:40 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +    private boolean hasNotClass(Class clazz) {
hasNotClass가 의미가 명확하지 않은 것 같아요 :)

2019-11-10 12:40 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +            Constructor<?> injectedConstructor = BeanFactoryUtils.getInjectedConstructor(clazz);
injectedConstructor가 instantiateBean까지 사용되지 않는데 지금 생성해서 넘겨줄 필요가 있는지 고민이 드네요. :)

2019-11-10 12:40 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +    }
bean을 생성하고 beans에 넣는 행위가 
putInstance에서와 중복되는 것 같아요. :)
두개의 getBeanOrDefault를 사용할 필요 없이 객체를 인스턴스화해서 돌려주고 
putInstance에서 putIfAbsent의 로직들을 수행하면 더 간결화되지 않을까요?

2019-11-10 12:40 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +    public Map<Class<?>, Object> getBeans(Class<? extends Annotation> annotation) {
맵 자체를 돌려주는 메서드보다, 해당 어노테이션 가지고있는 클래스를 반환하고 getBean 메서드를 활용해 돌려주는게 좀 더 역할이 명확하지 않을까요?

2019-11-10 12:40 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/scanner/BeanScanner.java
> +        return scanAnnotation(Controller.class, Service.class, Repository.class);
Controller.class, Service.class, Repository.class에 대해서 하나의 상수로 관리해보면 어떨까요?

2019-11-10 12:40 UTC, phs1116 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>      }
di를 구현했으니 이 또한 빈으로 활용해보면 어떨까요? :)

2019-11-10 12:40 UTC, phs1116 commented on slipp/src/main/java/slipp/SlippWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerMapping(new AnnotationHandlerMapping(beanFactory.getBeans(Controller.class)));
AnnotationHandlerMapping에 beanFactory를 주입하여 사용하는 방법도 있을 것 같아요. :)
어떤 어노테이션으로 매핑을 가져오는지는 AnnotationHandlerMapping 내부의 관심사이지 Initializer에서 책임질 역할일까요? :)

2019-11-10 12:40 UTC, phs1116 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AbstractNewController.java
> +public abstract class AbstractNewController {
현재 컨트롤러가 특정 추상체에 의존하지 않도록 구현이 되어있는데 다시 추상체를 생성할 필요가 있을까요?

2019-11-11 06:11 UTC, yuyu154 commented on slipp/src/main/java/slipp/SlippWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerMapping(new AnnotationHandlerMapping(beanFactory.getBeans(Controller.class)));
AnnotationHandlerMapping에서는 패키지 경로만 인자로 받아 내부에서 BeanScanner, BeanFactory를 이용하는 방식으로 변경했습니다.

2019-11-11 06:19 UTC, yuyu154 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +    }
메소드에 중복된 부분도 많고 이해하기 힘든 부분이 많아서 메소드를 변경했습니다.

2019-11-11 06:33 UTC, yuyu154 commented on nextstep-di/src/main/java/nextstep/di/scanner/BeanScanner.java
> +        return scanAnnotation(Controller.class, Service.class, Repository.class);
```   
 private static final Collection<Class<? extends Annotation>> annotations =
            Arrays.asList(Controller.class, Service.class, Repository.class);
``` 
일단 위와 같은 방식으로 BeanScanner에서 상수로 관리하도록 설정했습니다.

2019-11-11 14:04 UTC, yuyu154 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>      }
설정했습니다! 감사합니다

2019-11-11 14:14 UTC, yuyu154 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AbstractNewController.java
> +public abstract class AbstractNewController {
```slipp.controller```패키지 에서  HomeController나 UserController에서 AbstractNewController를 상속하는 부분을 제거했습니다.

2019-11-11 14:33 UTC, phs1116 approved these changes
안녕하세요! 르윈.
그 사이에 코드가 상당히 많이 정리가 됬네요! 👍 
구현 잘해주셨습니다.
이번 단계 머지하도록 하겠습니다. :)
사소한 피드백 추가했는데 다음 단계 참고해주세요!

2019-11-11 14:33 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +    public Set<Class<?>> getControllers() {
Controller뿐만 아닌 여러 조건에 해당하는 빈 클래스 Set을 리턴하도록 수정해볼수도 있을 것 같네요. :)

2019-11-11 14:33 UTC, phs1116 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AbstractNewController.java
> +public abstract class AbstractNewController {
넵넵 안쓰는 클래스면 이제 삭제해도 될 것 같네요. :)

2019-11-11 14:33 UTC, merged