[DI - Step 2] 쉐이크반 미션 제출합니다.
woowacourse/jwp-di pull request #48
Opened 2019-11-11 13:20 UTC by vsh123

안녕하세요!!

DI step-2 미션 구현하여 리뷰 요청드립니다!
이번 미션을 구현하며 다음과 같은 내용에 대해 고민하며 적용해 보았습니다.

1.  BeanDefinition class
 - Method를 Bean을 관리하는 MethodoBeanDefinition, 기본 어노테이션(Controller, Service, Repoository)를 관리하는 DefaultBeanDefinition을 구현했습니다.

2. ComponentScan 적용
 - 현재 ApplicationContext에서 getgetPackages()를 통해 ComponentScan의 value들을 가져오고 있는데 ApplicatioinContext에서 해당 기능을 수행하는 것이 맞는지 의문이 들어 해당 부분 문의드립니다!

이번 미션도 잘 부탁드리겠습니다!!!

2019-11-13 14:08 UTC, hongsii requested changes
쉐이크반 리뷰가 늦어서 죄송합니다 ㅠㅠ
요구사항을 전체적으로 잘 구현해주셨네요 👍 
몇 가지 피드백드렸으니, 참고해서 반영해주세요!

2019-11-13 14:08 UTC, hongsii commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        createDefaultBean((DefaultBeanDefinition) beanDefinition);
Bean을 찾는 방법에 따라 다른 정의 방식을 상속을 통해 추상화하신 것은 잘하셨습니다. 👍 

추가적으로 `public Object instantiate(Object... params)` 와 같은 추상 메서드를 `BeanDefinition` 클래스에 만들고 각 구현체에게 오브젝트를 생성하는 책임을 위임해 분기문을 제거해보면 어떨까요?
이와 같이 다형성을 활용한다면 `BeanFactory` 의 복잡도를 낮출 수 있을 듯 합니다.

2019-11-13 14:08 UTC, hongsii commented on nextstep-di/src/main/java/nextstep/di/factory/ApplicationContext.java
> +    private Object[] getPackages() {
`ClasspathBeanScanner` 는 패키지에서 특정 어노테이션이 설정된 클래스를 찾는 역할을 하고 있으며, 이런 클래스를 찾는 스캐너를 초기화하는 역할을 `ApplicationContext` 가 하고 있기 때문에 여기서 스캐너를 초기화하기 위한 값을 만드는 것이 이상하게 보이진 않습니다.
다만, 검색을 위한 패키지를 `basePackage` 라는 이름으로 사용하고 있습니다. 이 메서드에서도 모듈 내에서 사용 중인 용어로 통일해 `getBasePackages` 와 같은 네이밍으로 사용한다면 더 좋을 듯 해요.

2019-11-13 14:08 UTC, hongsii commented on nextstep-di/src/main/java/nextstep/di/factory/ApplicationContext.java
> +    public void initialize() {
이 로직은 생성자에서 해줘도 충분할 것 같아요!
생성자에서 해준다면 `configurations` 를 멤버변수로 만들지 않아도 됩니다.

2019-11-14 04:44 UTC, vsh123 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        createDefaultBean((DefaultBeanDefinition) beanDefinition);
`instantiate()` 매개 변수를 params로 넘기면 `BeanFactory`에서 해당 리턴 값을 꺼내어  ParametersType을 확인하는  작업을 해야 하기 때문에  'BeanFactory`를 인자로 넘기어  `BeanDefinition`에서 필요시 getBean을 하는 방식으로 변경을 해보았는데 혹시 이에 대해서 어떻게 생각하시는지 의견  주시면 감사하겠습니다!

2019-11-14 04:45 UTC, vsh123 commented
홍시 안녕하세요!
보내주신 피드백 반영하여 다시한번 리뷰 요청드립니다!!

혹시 수정사항에 대해 이상이 있으시면 언제든지 연락 부탁드리겠습니다!!

감사합니다 :)

2019-11-17 09:16 UTC, hongsii requested changes
피드백 반영 잘해주셨네요!
간단한 피드백 한가지 드렸으니, 확인하셔서 반영해주세요!

2019-11-17 09:16 UTC, hongsii commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactory.java
> +        throw new RuntimeException();
인터페이스를 체크하는 분기문을 앞에 배치하면 아래와 같은 Optional의 안티패턴(isPresent-get) 을 사용하지 않고 Optional의 `map(...)`, `orElseThorw(...)` 를 활용할 수 있을 듯 합니다!

``` java
if (maybeBeanDefinition.isPresent()) {
    return maybeBeanDefinition.get();
}
```

* [참고](https://dzone.com/articles/optional-ispresent-is-bad-for-you)

2019-11-17 09:16 UTC, hongsii commented on nextstep-di/src/main/java/nextstep/di/factory/DefaultBeanDefinition.java
> +        return constructor.newInstance(parameters.toArray());
`BeanFactory` 값을 꺼내지 않기 위해 파라미터로 전달하는 방식 적용 👍 
다만, 위와 같이 적용함으로써 `BeanFactory` 와 `BeanDefinition` 이 단뱡향 구조에서 서로 의존성을 가지는 양방향구조가 되었습니다. 서로 변경이 일어나면 영향이 발생합니다.
그리고 위 로직은 `MethodBeanDefinition` 에 중복된 로직이 있습니다. 중복을 제거해보면 좋을 듯 합니다.

2019-11-18 02:36 UTC, vsh123 commented on nextstep-di/src/main/java/nextstep/di/factory/DefaultBeanDefinition.java
> +        return constructor.newInstance(parameters.toArray());
아! 의존성에 대한 생각을 고려하지 못했네요 ㅠㅠ
의존성을 단방향으로 가져가게끔 변경을 진행하였습니다!

이렇게 변경하니 중복된 로직도 제거가 되었습니다..!!! 감사합니다 :)

2019-11-18 02:40 UTC, vsh123 commented
안녕하세요!!

보내주신 피드백 반영하여 다시 한번 리뷰요청드립니다!

확실히 피드백 반영을 하니 코드의 가독성이나. 책임에 대해서 더 깔끔해진 것 같습니다~!!!!!!!!
너무 감사드립니다!

2019-11-19 13:24 UTC, hongsii approved these changes
피드백 반영 잘해주셨네요! 노력하신만큼 코드가 좋아진게 눈에 보이네요! 💯 
2단계까지 고생많으셨습니다. 머지하겠습니다! =)

2019-11-19 13:25 UTC, merged