[DI - Step 2] 유니 미션 제출합니다.
woowacourse/jwp-di pull request #50
Opened 2019-11-11 14:39 UTC by yunheehyeon

2019-11-14 13:17 UTC, phs1116 requested changes
안녕하세요! 유니.
매우 깔끔하게 잘 구현해주셨네요.
전체적으로 추상화도 매우 잘해주셨습니다. 👍 
몇가지 간단한 피드백 추가했는데요, 참고 부탁드릴게요. :)

2019-11-14 13:17 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/scanner/ClasspathBeanScanner.java
> +    }
initialize도 추상화 할 수 있어보이네요. :)

2019-11-14 13:17 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +        new ConfigurationBeanScanner(beanFactory, basePackage);
해당 Scanner에 대해서 외부에서 추가로 주입하거나 설정할 수 있도록 열려있는 구조로 구현해보면 좋을 것 같네요. :)

2019-11-14 13:17 UTC, phs1116 commented on slipp/src/main/java/slipp/configuration/MyConfiguration.java
> +@ComponentScan(value = {"slipp"})
👍

2019-11-14 13:17 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/scanner/ClasspathBeanScanner.java
> +    public ClasspathBeanScanner(BeanFactory beanFactory, Object... basePackage) {
ClasspathBeanScanner의 생성과 beanFactory에 주입하기위한 scan의 행위가 생성자로 묶여있는건 책임상 적합하지 않아보이네요. :)

2019-11-14 13:17 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +        Object[] basePackage = configuration.getAnnotation(ComponentScan.class).value();
복수개의 configuration을 설정하고 복수개의 ComponentScan도 있을 수 있을 것 같은데 맞춰서 수정해보면 어떨까요? :)

2019-11-14 13:17 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +    public void initialize(Object... basePackage) {
해당 메서드는 private으로 닫던가 기능을 분리하는게 좋을 것 같네요.
생성자를 통해 주입된 configruation이 무색하게 이 공개된 메서드를 사용하면 사이드 이펙트가 크게 발생할 여지가 보이네요.

2019-11-14 13:17 UTC, phs1116 commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +    }
getter를 통하지 말고, BeanFactory로 공통적으로 사용되는 인터페이스를 추출하고 BeanFactory에 행위를 위임해보면 어떨까요?

2019-11-30 14:42 UTC, yunheehyeon commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +        new ConfigurationBeanScanner(beanFactory, basePackage);
반영했습니다.

2019-11-30 14:42 UTC, yunheehyeon commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +        Object[] basePackage = configuration.getAnnotation(ComponentScan.class).value();
반영했습니다.

2019-11-30 14:44 UTC, yunheehyeon commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +    public void initialize(Object... basePackage) {
BeanScanner 를 외부에서 주입하도록 수정해서 public 를 유지하고 외부에서 호출했습니다.

2019-11-30 14:46 UTC, yunheehyeon commented on nextstep-di/src/main/java/nextstep/di/ApplicationContext.java
> +    }
ApplicationContext이 BeanFactory을 확장하고 있다고 생각해서, 구현된 BeanFactoryImpl을 상속받고 행위를 위임했습니다.

2019-11-30 14:47 UTC, yunheehyeon commented on nextstep-di/src/main/java/nextstep/di/scanner/ClasspathBeanScanner.java
> +    public ClasspathBeanScanner(BeanFactory beanFactory, Object... basePackage) {
나중에 basePackage와 beanFactory를 따로 받도록 분리했습니다.

2019-12-02 15:32 UTC, phs1116 approved these changes
안녕하세요! 유니.
구현 매우 잘해주셨습니다.
DI 이만 머지할게요. :) 
고생 많으셨습니다.

2019-12-02 15:32 UTC, merged