[DI - Step 2] 이바 미션 제출합니다.
woowacourse/jwp-di pull request #61
Opened 2019-11-16 11:39 UTC by seonghun127

안녕하세요 후니! 리뷰이 이바입니다.
스텝 1에서 주신 피드백을 모두 반영해보고 저만의 생각대로 스텝 2를 구현해봤습니다.

기본적인 구조는 이렇습니다.

* ApplicationContext
  * Bean의 생명주기를 관리하기 위한 명세 인터페이스
* MvcApplicationContext
  * ApplicationContext 인터페이스를 상속하면서 차후에 Controller 빈들을 반환하는 기능이 추가된 확장 인터페이스
* AnnotationConfigApplicationContext
  * 위 두 인터페이스를 구현하는 구현체
  * 어노테이션 기반으로 빈을 등록, 관리하는 클래스
---
* BeanScanner
  * 해당 패키지 경로에 있는 클래스를 빈으로 등록하기 위한 명세 인터페이스
* ClassBeanScanner
  * `Controller.class, Service.class, Repository.class` 어노테이션이 붙어있는 클래스를 스캔
  * 추가로 `ComponentScan` 어노테이션이 있다면 `basePackages` 속성 값에 있는 클래스들도 같이 스캔합니다.
* MethodBeanScanner
  * `Configuration` 파일의 `@Bean` 이 붙어있는 메서드의 반환값을 스캔
---
* BeanCreator
  * 빈으로 등록될 클래스(@Component, @Bean 기반 모두)를 인스턴스화 시키기 위한 명세 인터페이스
* ClassBeanCreator
  * `@Component` 기반으로 빈을 생성
* MethodBeanCreator
  * `@Bean` 기반으로 빈을 생성
---
* BeanFactory
  * Bean으로 등록될 클래스를 인스턴스화(생성) 시키는 클래스
  * `BeanScanner` 를 통해 스캔된 빈들을 어떻게 생성할지 `BeanCreator` 로 명세된 `beanCreators` 를 가지고 실제 빈을 생성하는 역할을 담당
  * 유틸성 클래스의 느낌이 강한 느낌이 들지만 상태를 가짐으로써 수월한 유지보수의 이점을 가지고자 인스턴스 클래스로 두었습니다.
    * `private Map<Class<?>, BeanCreator> beanCreators;` 와 같은 상태 필드를 가지고 있고 이 필드를 가지고 여러 메서드가 사용하고 있는 상황입니다.

클래스 구분과 그 역할을 최대한 명확히 해보려고 노력했습니다.
구현에 미흡한 부분이 많아 더욱더 많이 지적해주시면 감사하겠습니다!
추후에 질문들은 DM으로 보낼게요 ㅎ_ㅎ

2019-11-20 00:13 UTC, jeonghoon1107 requested changes
안녕하세요 이바!
구현한 내용에 대해 정리를 깔끔하게 잘 하셨네요 💯 
아쉬운 점이 있어서 몇가지 피드백을 남겼으니 확인부탁드려요 :)

2019-11-20 00:13 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/SlippWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerMapping(new AnnotationHandlerMapping(context.getControllers()));
DispatcherServlet에게 context를 주입해 내부에서 처리하면 어떨까요?

2019-11-20 00:13 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/ClassBeanScanner.java
> +        Set<Class<?>> types = getTypesAnnotatedWith(reflections, Controller.class, Service.class, Repository.class, Configuration.class);
ComponentScan이 지정된 패키지를 기준으로 빈을 탐색하는 것이 좋지 않을까요?
 getTypesFromComponentScan 메서드에서 모든 어노테이션이 달린 Set을 순회하면서 ComponentScan을 찾지 않아도 될 것 같아요.

2019-11-20 00:13 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/ClassBeanScanner.java
> +    private Set<Class<?>> getTypesFromComponentScan(Set<Class<?>> types) {
`getTypesAnnotatedWith(new Reflections(packages, Controller.class, Service.class, Repository.class))`
해당 코드가 scan 메서드와 중복이네요! scan 안에서는 해당 메서드를 부르고 있는데..

2019-11-20 00:13 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/ClassBeanScanner.java
> +                .flatMap(Set::stream)
`flatMap(Collection::stream)`

2019-11-20 00:13 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/MethodBeanScanner.java
> +            throw new ObjectInstantiationFailException(e);
BeanInstantiationFailException 이 더 명확할 것 같아요.

2019-11-20 00:13 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/AnnotationConfigApplicationContext.java
> +        beans = new BeanFactory(creators, beans).initializeBeans();
initializeBeans 라는 메서드가 BeanFactory가 가지고 있는 bean을 리턴해주는 것은 메서드명과 맞지 않는 것 같아요. (메서드 명 그대로 초기화 작업만 하면 좋을 것 같아요.)

따로 인스턴스 변수를 만들지않고 BeanFactory 자체를 인스턴스 변수로 사용해도 좋을 것 같아요.
getBean 등의 메서드는 BeanFactory안에 구현되어도 될 것 같아요.

2019-11-20 00:13 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/AnnotationConfigApplicationContext.java
> +    public Map<Class<?>, Object> getControllers() {
해당 메서드를 interface로 추출하는 것이 의미가 있나요?

2019-11-23 05:06 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/AnnotationConfigApplicationContext.java
> +    public Map<Class<?>, Object> getControllers() {
기본적으로 빈을 관리하는 역할을 `ApplicationContext` 인터페이스에게 위임한 상황입니다.

그런데 현재는 어노테이션 기반으로 빈을 생성하고 관리하기 때문에 `HandlerMapping`에게 `@Controller` 어노테이션이 달려있는 빈을 전달해줘야하는 구조입니다.
이는 빈들을 관리하는 `ApplicationContext`가 해줘야한다고 생각하는데 여기에 `getControllers()` 메서드까지 추가하게 되면 후에 어노테이션 기반이 아닌 다른 방식의 컨텍스트를 생성해야하는 과정에 불필요하게 `getControllers()`를 구현해야하는 상황을 방지하기 위함입니다.

그래서 어노테이션 기반의 컨텍스트를 생성하기위한 규약으로 `MvcAnnotationContext` 인터페이스를 따로 뺐습니다.

2019-11-23 06:44 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/ClassBeanScanner.java
> +        Set<Class<?>> types = getTypesAnnotatedWith(reflections, Controller.class, Service.class, Repository.class, Configuration.class);
반영했습니다!

저는 후니 피드백에 대해서 `@ComponentScan`이 없는 경우에 오류를 던지는 것이 맞을까 의문이 들었습니다. 이를 대비하여 우선적으로 `AnnotationConfigApplicationContext`가 인자로 받은 `basePackages`를 기준으로 여러 컴포넌트를 조회하는 방식을 두었습니다.

여기에 추가적으로 `@ComponentScan` 어노테이션이 있다면 그 어노테이션 갖고 있는 `basePackages` 속성값으로 해당 경로에 있는 컴포넌트를 찾는 방식의 `scan()`를 하는 방식을 선택했습니다.

`basePackages` 외부에 존재하는 패키지의 클래스도 같이 빈으로 등록되길 원하는 경우에 대하여 `@ComponentScan`을 통해 해결할 수 있는 방식을 기대하기 위함입니다.

2019-11-23 06:50 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/ClassBeanScanner.java
> +    private Set<Class<?>> getTypesFromComponentScan(Set<Class<?>> types) {
```
public Map<Class<?>, BeanCreator> scan(Object... basePackages) {
        Set<Class<?>> types = Sets.newHashSet();

        // ComponentScan 기준으로 탐색
        Set<Class<?>> componentScans = getTypesAnnotatedWith(new Reflections(basePackages), ComponentScan.class);
        for (Class<?> clazz : componentScans) {
            String[] basePackage = clazz.getAnnotation(ComponentScan.class).basePackages();
            types.addAll(getTypesAnnotatedWith(new Reflections(basePackage), Controller.class, Service.class, Repository.class));
        }

        return Maps.asMap(types, ClassBeanCreator::new);
}
```

원래는 후니의 피드백을 보고 위와 같은 방식으로 변경하려 했습니다. 하지만 `@ComponentScan`이 없는 경우에 대해서 그냥 오류를 던지는게 개발자가 사용하기 편한 프레임워크인가라는 생각이 자꾸 들더군요. 그래서 
`@ComponentScan`이 없는 경우에 기본 경로를 기준으로 스캔을 할 수 있도록 현재 코드로 적용했습니다.

2019-11-23 06:53 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/MethodBeanScanner.java
> +            throw new ObjectInstantiationFailException(e);
반영했습니다!

2019-11-25 23:41 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/AnnotationConfigApplicationContext.java
> +        beans = new BeanFactory(creators, beans).initializeBeans();
반영했습니다!

`initializeBeans()`메서드는 `BeanFactory` 클래스 생성자에서 호출하고 생성된 빈들을 `getBeans()`로 제공하는 식으로 변경했습니다.

2019-11-26 00:18 UTC, seonghun127 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/ClassBeanScanner.java
> +                .flatMap(Set::stream)
위 로직은 제거했습니다!

2019-11-26 00:37 UTC, seonghun127 commented on slipp/src/main/java/slipp/SlippWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerMapping(new AnnotationHandlerMapping(context.getControllers()));
`DispatcherServlet`가 context를 가지고 있음으로써 어떤 부분이 더 나아지는지 궁금합니다!

2019-11-29 16:09 UTC, jeonghoon1107 approved these changes
안녕하세요 이바!
리팩토링을 깔끔하게 잘 해주셨네요 👍 
고민을 많이 하시는 모습이 보기 좋았습니다.
미션 진행하느라 고생 많으셨습니다 :)

2019-11-29 16:09 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/SlippWebApplicationInitializer.java
> +        MvcApplicationContext context = new AnnotationConfigApplicationContext("slipp");
WebServerLauncher.class의 basePackage를 주어도 될 것 같아요!

2019-11-29 16:09 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/SlippWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerMapping(new AnnotationHandlerMapping(context.getControllers()));
addHandlerMapping이나 addHandlerAdapter 등 DispatcherServlet을 초기화하는 부분은 해당 객체 밖에서 하는 것보다 안에서 하는 것이 더 좋겠네요!
DispatcherServlet안에서 context를 생성하라는 것은 아닙니다 :)

2019-11-29 16:09 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/AnnotationConfigApplicationContext.java
> +        beans = new BeanFactory(creators, beans).initializeBeans();
그렇다면 ApplicationContext가 BeanFactory를 상속하는 것도 좋겠네요!

2019-11-29 16:09 UTC, jeonghoon1107 commented on nextstep-di/src/main/java/nextstep/di/factory/beanscanner/ClassBeanScanner.java
> +    private Set<Class<?>> getTypesFromComponentScan(Set<Class<?>> types) {
기본 경로로 스캔하는 것은 좋은 방법같네요 👍

2019-11-29 16:09 UTC, merged