[DI - step 2] 닉 미션 제출합니다.
woowacourse/jwp-di pull request #66
Opened 2019-11-18 13:34 UTC by wbluke

안녕하세요 브리! 감기에 걸려서 한주 늦었습니다ㅠㅠ
마지막 미션도 잘 부탁드립니다ㅎㅎ!

```java
beanFactory = new BeanFactory();

ConfigurationBeanScanner configurationBeanScanner = new ConfigurationBeanScanner(beanFactory);
configurationBeanScanner.scan();
configurationBeanScanner.registerBeans();

List<String> componentScanPackages = configurationBeanScanner.findPackagesInComponentScan();
ClassPathBeanScanner classPathBeanScanner = new ClassPathBeanScanner(beanFactory);
classPathBeanScanner.scan(componentScanPackages);

beanFactory.initialize();
```

step2의 핵심 흐름은 위와 같습니다.
1. BeanFactory 생성
2. ConfigurationBeanScanner에 BeanFactory를 주입하면서 생성 후 @Configuration 스캔
3. @Configuration 클래스의 @Bean 애노테이션 붙어있는 Method로 BeanFactory에 Bean 후보 등록
4. ConfigurationBeanScanner에서 @Configuration 클래스의 @ComponentScan 안에 등록된 패키지 검색
5. ClassPathBeanScanner에 BeanFactory를 주입하면서 생성
6. ClassPathBeanScanner가 해당 패키지를 받아서 BeanType 스캔 후 BeanFactory에 Bean 후보 등록
7. BeanFactory.initialize()로 빈 생성 및 캐싱

특히 구현 시에 가장 복잡해서 어려웠던 부분이 step1에서 구현했던 BeanFactory의 Bean 등록 로직에
새로 추가된 Config 클래스 내의 Method 기반 @Bean 등록 로직을 합치는 부분이었습니다.
Bean 인스턴스 생성하는 부분을 Constructor<?>와 Method의 공통 부모인 Executable 추상 클래스로 묶어서 처리해 보았습니다.

2019-11-20 11:35 UTC, byjo requested changes
닉 안녕하세요~ 이벤트 (및 장애ㅠㅠ) 대응으로 인해 리뷰가 늦었어요. 죄송합니다. 
2단계 요구사항을 위한 구현 잘 진행 하셨어요! 👍
다만, 프레임워크(라이브러리) 모듈 사이의 의존도를 낮추는 방향으로 가면 더 좋을 것 같아 피드백 드렸어요.
리팩토링 하시다 궁금하거나 이야기 나눠보고 싶은 사항 있으면 편하게 이야기 주세요 😊

2019-11-20 11:35 UTC, byjo commented on nextstep-di/src/main/java/nextstep/di/ClassPathBeanScanner.java
> +    public void scan(Object... basePackage) {
`BeanFactory`에 의존성을 갖고 bean 후보를 등록하는 Scanner들의 로직을 추상화 해보면 어떨까요?

2019-11-20 11:35 UTC, byjo commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +@Component
이 설정으로 인해 Jdbc 라이브러리가 di 프레임워크에 의존성을 갖게 되지 않을까요?
JdbcTemplate을 사용하는 개발자는 항상 di 프레임워크도 함께 사용해야 하는 걸까요?

2019-11-20 11:35 UTC, byjo commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        classPathBeanScanner.scan(componentScanPackages);
이번에 추가된 기능이 정상적으로 동작하기 위해서는 `ConfigurationBeanScanner`가 먼저 스캔되고, 스캔을 통해 알게 된 package를 `ClassPathBeanScanner` 에게 넘겨 주어야 하네요.
이러한 di를 위한 로직을 다른 모듈(mvc)에 속해 있는 `AnnotationHandlerMapping` 이 세부적으로 알고 있어야 할까요?
만약 Scanner에 변경이 생겼을 때, mvc 모듈도 함께 변경되어야 한다면 확장성이 점점 떨어지지 않을까요?

이러한 부분을 해결하기 위해 스캐너간 관계를 맺는 새로운 객체를 설계해보면 좋을 것 같습니다.

2019-11-20 11:35 UTC, byjo commented on slipp/src/main/java/slipp/JdbcConnectionConfig.java
> +    public Connection getConnection(DataSource dataSource) {
Connection을 bean으로 생성하면 멀티 환경에서의 지원이 어렵지 않을까요?

2019-12-02 14:45 UTC, wbluke commented
안녕하세요 브리 :)
피드백 반영하였습니다ㅎㅎ BeanScanner의 추상화 과정에서는 DM으로 말씀드린 사항 중 2번째 안으로 진행해 보았습니다. 저도 명세를 구체화하는 것을 선호해서요!
생성자가 아닌 메소드에서 BeanFactory를 받아서 Bean을 등록하도록 명시하였습니다.
다시 한 번 잘 부탁 드립니다! :)

2019-12-03 10:17 UTC, byjo approved these changes
Scanner와 ApplicationContext 추상화 잘 하셨네요 👍
리팩토링 하면서 의미있는 고민을 하셨기를 바라며 머지할게요.
고생 많으셨습니다! 👏

2019-12-03 10:17 UTC, merged