[DI - Step 2] 션 미션 제출합니다.
woowacourse/jwp-di pull request #77
Opened 2019-12-16 15:22 UTC by os94

DI - Step 2 미션 제출합니다.

쉽지않네요,, 늦어져서 죄송합니다..😓
마지막미션, 그동안 몇개월간 소중한 코드리뷰 정말 감사했습니다 (_ _)
말로 표현못할만큼 많이 성장할수있었던것 같습니다 👍

2019-12-16 16:57 UTC, os94 commented on nextstep-di/src/main/java/nextstep/di/bean/factory/BeanFactory.java
> +    private Object createBean(Class<?> clazz) {
private 메서드로 분리할수도있었는데,
이렇게 합친상태로 두는것이 전체 재귀흐름이 더 잘보이는것 같아서
이 상태로 유지해보았습니다!

2019-12-19 15:21 UTC, jihan805 requested changes
안녕하세요~ 깔끔하게 잘 구현하셨어요 💯 
간단한 피드백 남겼으니 확인해주세요 !

2019-12-19 15:21 UTC, jihan805 commented on nextstep-di/src/main/java/nextstep/ReflectionUtils.java
> +                .filter(constructor -> constructor.getParameterCount() == 0)
상수를 사용할 수 있었을 것 같아요!

2019-12-19 15:21 UTC, jihan805 commented on nextstep-di/src/main/java/nextstep/di/bean/factory/BeanFactory.java
> +    private Object createBean(Class<?> clazz) {
저는 이 메서드가 하는 역할이 너무 많다고 생각해요.
일부 구현은 메서드를 이용해 분리하고, 원하는 의도대로 재귀의 흐름을 잘 보이게 할 수 있을 것 같은데 
한번 더 고민해보면 어떨까요?

2019-12-19 15:21 UTC, jihan805 commented on nextstep-di/src/main/java/nextstep/di/bean/ApplicationContext.java
> +public class ApplicationContext {
ApplicationContext 구현 👍

2019-12-19 15:21 UTC, jihan805 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        Map<Class<?>, Object> controllers = applicationContext.getBeanFactory().getBeansAnnotatedWith(Controller.class);
.을 두번이나 체이닝하고 있는데, 이를 줄이면 어떨까요?

2019-12-20 17:22 UTC, os94 commented on nextstep-di/src/main/java/nextstep/di/bean/factory/BeanFactory.java
> +    private Object createBean(Class<?> clazz) {
일부로직을 분리해보니 생각보다 괜찮은것같습니다 ㅎㅎ
가독성도 높아진것같습니다 감사합니다 :)

2019-12-20 17:22 UTC, os94 commented on nextstep-di/src/main/java/nextstep/ReflectionUtils.java
> +                .filter(constructor -> constructor.getParameterCount() == 0)
반영했습니다!

2019-12-20 17:23 UTC, os94 commented on nextstep-mvc/src/main/java/nextstep/mvc/tobe/AnnotationHandlerMapping.java
> +        Map<Class<?>, Object> controllers = applicationContext.getBeanFactory().getBeansAnnotatedWith(Controller.class);
안그래도 ApplicationContext내에 byPass 메소드를 만들어줄지말지 고민했는데
역시 만들어주는게 나은것같아요 ㅎㅎ 👍

2019-12-20 17:24 UTC, os94 commented
리뷰 반영했습니다! 감사합니다.

2019-12-23 20:34 UTC, merged