[DI - Step2] 버디 미션 제출합니다.
woowacourse/jwp-di pull request #89
Opened 2019-12-26 04:00 UTC by imkimheejoo

리뷰어님 늦게 제출해서 죄송합니다. ㅜㅜ

2019-12-26 09:56 UTC, young891221 requested changes
안녕하세요, 버디!
오랜만에 PR 주셨군요ㅎㅎ
몇 가지 피드백 남겼습니다. 확인 부탁드립니다~!

2019-12-26 09:56 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/ApplicationContext.java
> +            preInitiateBeans.putAll(beanScanner.scanBeans());
bean 클래스가 중복되었을 때의 처리에 대해 고민해 보면 어떨까요?

2019-12-26 09:56 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/ApplicationContext.java
> +            preInitiateBeans.putAll(beanScanner.scanBeans());
중복된 처리에 대한 테스트도 추가되면 좋아 보입니다.

2019-12-26 09:56 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/BeanFactoryUtils.java
> +    public static Optional<Class<?>> findConcreteClass(Class<?> injectedClazz, Set<Class<?>> preInstanticateBeans) {
👍

2019-12-26 09:56 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/ClasspathBeanScanner.java
> +        Set<Class<?>> preInitiatedBeans = new HashSet<>();
중복 제거를 위해 map, set을 동시에 사용하였는데요. 불필요하게 공간낭비가 발생합니다.(물론 미비하겠지만...)
map만 사용하고 조건절을 통해 중복 여부를 체크해 보는것은 어떨까요?

2019-12-26 09:56 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/ConstructorDefinition.java
> +                e.printStackTrace();
`e.printStackTrace()`로 에러처리하는 습관은 안좋은 습관입니다. (성능에 좋지 않습니다)
로깅을 남기고 에러를 반환하는 습관을 기르시는게 추후 실무에 도움이 됩니다.

2019-12-26 09:56 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/ConstructorDefinition.java
> +            throw new InvalidBeanException();
이쪽도 마찬가지로 해당하는 에러에 대한 로깅 + throwing이 필요합니다.

2019-12-26 09:56 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/MethodDefinition.java
> +            throw new InvalidBeanException();
Ditto

2019-12-27 01:21 UTC, imkimheejoo commented on nextstep-di/src/main/java/nextstep/di/factory/ClasspathBeanScanner.java
> +        Set<Class<?>> preInitiatedBeans = new HashSet<>();
reflections.getTypesAnnotatedWith(clazz) 를 stream걸어서 map으로 변환하려 했는데 되지 않았습니다.. 우선 메서드로 분리만 했습니다.. ㅠㅠ

2019-12-27 01:21 UTC, imkimheejoo commented on nextstep-di/src/main/java/nextstep/di/factory/ConstructorDefinition.java
> +                e.printStackTrace();
로거를 추가하고 에러를 반환하는 것으로 수정했습니다.
로거에 메시지를 추가하는 과정에서 우선은 에러메시지를 하드코딩하게 했는데 던지는 예외를 먼저 초기화 하고 그 예외를 logger에 담아야 하는지 아니면 실제 던져진 예외에 대한 정보를 담아야 하는지 모르겠습니다...

2019-12-28 08:04 UTC, imkimheejoo commented on nextstep-di/src/main/java/nextstep/di/factory/ApplicationContext.java
> +            preInitiateBeans.putAll(beanScanner.scanBeans());
ClassPathBeanScanner, ConfigurationBeanScanner에 중복확인 로직 추가 및 테스트 하였습니다!

2019-12-28 08:26 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/definition/ConstructorDefinition.java
> +                throw new NotFoundConstructorException();
아래와 같은 형식으로 만들어주면 효율적으로 디버깅이 가능합니다.
```java
log.error("ConstructorDefinition ConstructorDefinition can't found construct");
throw new NotFoundConstructorException("ConstructorDefinition ConstructorDefinition can't found construct", e);
```

2019-12-28 08:26 UTC, young891221 commented on nextstep-di/src/main/java/nextstep/di/factory/ConstructorDefinition.java
> +                e.printStackTrace();
아래와 같은 형식으로 만들어주면 효율적으로 디버깅이 가능합니다.

```java
log.error("ConstructorDefinition ConstructorDefinition can't found construct");
throw new NotFoundConstructorException("ConstructorDefinition ConstructorDefinition can't found construct", e);
```

2019-12-28 08:27 UTC, young891221 approved these changes
버디! 리뷰 반영을 잘해주셨네요:) 💯 
에러처리에 대한 부분만 추가 코멘트 드렸는데 별도의 추가 개선은 불필요해 보여
이만 머지하겠습니다. 그동안 고생하셨어요~!

2019-12-28 08:27 UTC, merged